#ifndef EPISODEPREPARATION_GLOBAL_H
#define EPISODEPREPARATION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LSC_EPISODEPREPARATION_LIBRARY)
#  define LSC_EPISODEPREPARATIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LSC_EPISODEPREPARATIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // EPISODEPREPARATION_GLOBAL_H
