#ifndef APPLICATIONSTATEMACHINE_GLOBAL_H
#define APPLICATIONSTATEMACHINE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LSC_APPLICATIONSTATEMACHINE_LIBRARY)
#  define LSC_APPLICATIONSTATEMACHINESHARED_EXPORT Q_DECL_EXPORT
#else
#  define LSC_APPLICATIONSTATEMACHINESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // APPLICATIONSTATEMACHINE_GLOBAL_H
